### ISSUE TITLE
Problems Integrating With Oasis

### ISSUE THREAD

**Issue by craig-riecke** [janestreet/ppx_inline_test#3]
Switched over from pa_unit camlp4 extension, and changed the syntax of TEST -> let%test.  Trying to compile I get:

```
ppx_inline_test: extension is disabled because the tests would be ignored (the build system didn't pass -inline-test-lib)
```

I'm using Oasis and it's far from clear to me where to pass this argument, and what to use as a parameter (if any).

**Comment by diml** [comment]
Indeed, oasis itself cannot handle this. Sadly, it is currently quite complicated to do this. Following are a few ways of doing it.

Method 1 & 2 are a bit simpler and should deliver slightly better compilation speed, however they might not work depending on what other ppx rewriters you are using.

## Method 1

If you are only using Jane Street ppx rewriters, then a very simple solution is to install ppx\_jane and add write a _tags file containing:

```
<src/*.ml{,i}>: predicate(ppx_driver)
<src/*.ml{,i}>: pp(ppx-jane -dump-ast -inline-test-lib name_of_your_library)
# OASIS_START
# OASIS_STOP
```

The first line is an unfortunate hack, while the second is quite imple: it instruct the build system to pre-process every file in src/ with ppx-jane.

## Method 2

Similar to method 1, but instead of using all of ppx\_jane, you specify what you want. First, add this to your _oasis file:

```
XOCamlbuildPluginTags: package(ppx_driver.ocamlbuild)
```

then put this in your _tags file:

```
<**/*.ml{,i}>: predicate(ppx_driver)
<**/*.ml{,i}>: ppx-driver(ppx_inline_test+ppx_a_second_rewriter+ppx_a_third_rewriter -inline-test-lib name_of_your_library)
# OASIS_START
# OASIS_STOP
```

The _oasis line will enable the interpretation of `ppx-driver(...)` in the _tags file, which takes as argument a `+` separated list of ppx rewriters followed by additional command line arguments.

## Method 3

This method is the most complicated one but will work best if you are using rewriters that are not based on ppx\_driver.

First write a _tags file containing:

```
<**/*.ml{,i}>: inline_test_lib(name_of_your_library)
# OASIS_START
# OASIS_STOP
```

And a myocamlbuild.ml containing:

```ocaml
(* OASIS_START *)
(* OASIS_STOP *)

let dispatch = function
  | After_rules ->
    List.iter (fun tag ->
      pflag ["ocaml"; tag] "inline_test_lib" (fun s -> S [A "-ppxopt"; A s])
      ["ocamldep"; "compile"; "doc"]
  | _ -> ()

let () = Ocamlbuild_plugin.dispatch dispatch
```

**Comment by craig-riecke** [comment]
Thank you!  #1 worked because we only use one ppx - ppx_inline_test - in the actual test code.

**Comment by superbobry** [comment]
I've tried using method 2 and it failed with

```
ocamlfind ocamlc -c -g -annot -bin-annot -package ppx_inline_test -predicates ppx_driver -I src -o src/roaring.cmo src/roaring.ml
File "src/roaring.ml", line 38, characters 4-8:
Uninterpreted extension 'test'.
```

Here's the relevant line from `roaring.ml`

```
let%test _ = 1 == 2
```

and the rest of the configuration files

```
# _oasis
AlphaFeatures:         ocamlbuild_more_args
XOCamlbuildPluginTags: package(ppx_driver.ocamlbuild)

Library roaring
  Path:           src
  Modules:        Roaring
  BuildDepends:   ppx_inline_test

# _tags
<src/*.ml{,i}>: predicate(ppx_driver)
<src/*.ml{,i}>: ppx-driver(ppx_inline_test -inline-test-lib roaring)
# OASIS_START
<src/*.ml{,i,y}>: package(ppx_inline_test)
# ...
# OASIS_STOP
```

**Comment by diml** [comment]
Ha, actually the XOCamlbuildPluginTags only allows to use the library inside the ocamlbuild plugin, you need the manual calll to dispatch indeed

**Comment by superbobry** [comment]
Ah, I see, thanks!

**Comment by diml** [comment]
I updated the README for ppx_driver and other Jane Street ppx packages. Note that the new recommendation is slightly different: you should put `predicate(custom_ppx)` instead of `predicate(ppx_driver)`, although it should still work with `predicate(ppx_driver)`.

There is a new package [jane-street-tests](https://github.com/janestreet/jane-street-tests) with some scenarios using oasis. This will help make sure things still work moving forward and can be used as an example
